name: Flutter CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.13.0'
        channel: 'stable'

    - name: Get dependencies
      working-directory: ./client
      run: flutter pub get

    - name: Analyze code
      working-directory: ./client
      run: flutter analyze

    - name: Run tests
      working-directory: ./client
      run: flutter test

    - name: Build APK
      working-directory: ./client
      run: flutter build apk --debug

    - name: Build Web
      working-directory: ./client
      run: flutter build web

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: flutter-builds
        path: |
          client/build/app/outputs/flutter-apk/
          client/build/web/
